apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: backend-image
    newName: registry.gitlab.com/asrio24/asri-hub
    newTag: main
  - name: frontend-image
    newName: registry.gitlab.com/asrio24/asri-hub
    newTag: main
  - name: proxy-image
    newName: registry.gitlab.com/asrio24/asri-hub
    newTag: main

components:
  - ../../components/environments/backend/dev
  - ../../components/environments/proxy/dev
  - ../../components/init_containers/migrations
  - ../../components/init_containers/proxy_collect_static
  - ../../components/pull_policy/Always
  - ../../components/pullcred
  - ../../components/scale_strategy/replicas1

resources:
  - ../../base
