apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asri-hub

images:
  - name: backend-image
    newName: registry.gitlab.com/asrio24/asri-hub
    newTag: backend-latest
  - name: frontend-image
    newName: registry.gitlab.com/asrio24/asri-hub
    newTag: frontend-latest
  - name: proxy-image
    newName: registry.gitlab.com/asrio24/asri-hub
    newTag: proxy-latest
  - name: postgres-image
    newName: postgres
    newTag: latest
  - name: cat-cam-image
    newName: aler9/rtsp-simple-server
    newTag: latest

components:
  - ../../components/postgres
  - ../../components/postgres/environments/prod
  - ../../components/environments/backend/prod
  - ../../components/environments/proxy/prod
  - ../../components/ingress/production
  - ../../components/init_containers/migrations
  - ../../components/init_containers/proxy_collect_static
  - ../../components/pull_policy/Always
  - ../../components/pullcred
  - ../../components/scale_strategy/replicas1

resources:
  - ../../base
