apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName redis
spec:
  template:
    spec:
      containers:
        - name: *deploymentName
          image: redis-image
          ports:
            - containerPort: 6379
      securityContext:
        runAsUser: 999
        runAsGroup: 999
