- op: add
  path: /spec/template/spec/volumes
  value:
    - emptyDir: {}
      name: &etcCerts ca-certificates
    - name: &certSecretVolume external-api-ca
      secret:
        secretName: *certSecretVolume
        items:
          - key: external-api-ca.crt
            path: external-api-ca.crt
### NOTE: THIS PATCH ASSUMES THAT AT LEAST ONE INIT_CONTAINER IS ALREADY PRESENT
- op: add
  path: /spec/template/spec/initContainers/0
  value:
    name: update-ca-certificates
    image: backend-image
    command:
      - "/bin/bash"
      - "-c"
      - "update-ca-certificates && cp -r /etc/ssl/certs /updated-certs && ls -laF /updated-certs"
    volumeMounts:
      - name: *etcCerts
        mountPath: /updated-certs
      - name: *certSecretVolume
        mountPath: /usr/local/share/ca-certificates/visimo
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      privileged: true
###
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - mountPath: /etc/ssl/certs
      subPath: certs
      name: *etcCerts
    - mountPath: /usr/local/share/ca-certificates/visimo
      name: *certSecretVolume
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: REQUESTS_CA_BUNDLE
      value: /etc/ssl/certs/ca-certificates.crt
