apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName backend
spec:
  template:
    spec:
      containers:
        - name: *deploymentName
          image: backend-image
          ports:
            - containerPort: 8000
