apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: persistent_volume_claim_patch.yaml
    target:
      kind: PersistentVolumeClaim
      labelSelector: template=nfs-pvc
  - path: persistent_volume_patch.yaml
    target:
      kind: PersistentVolume
      labelSelector: template=nfs-pv
