apiVersion: v1
kind: PersistentVolume
metadata:
  name: &placeholder PLACEHOLDER
spec:
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  nfs:
    server: *placeholder
    # nfs.path should be specified when creating the volume object.
    # path:
