apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name PLACEHOLDER
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-provisioner
  # you may optionally specify spec.volumeName to link directly to a persistent volume
