apiVersion: apps/v1
kind: Deployment
metadata:
  name: &deploymentName frontend
spec:
  template:
    spec:
      containers:
        - name: *deploymentName
          image: frontend-image
          ports:
            - containerPort: 3000
